name: Build
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: textbook/git-checkout-submodule-action@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: NGINX/Quiche/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/nginx-quiche
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: NGINX/Quiche
          cache: true
