name: Build
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 4 * * *'
  push:
jobs:
  Build-Renovate-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: Renovate/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/renovate-alpine
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: Renovate
          cache: true
  Build-Altair-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: Altair/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/altair-alpine
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: Altair
          cache: true
  Build-Node-Alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: Node/Node-Alpine/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/node-alpine
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: Node/Node-Alpine
          cache: true
  Build-Telnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: Telnet/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/telnet
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: Telnet
          cache: true
  Build-Git-Alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: Git/Alpine/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/git:alpine
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: Git/Alpine
          cache: true
  Build-Curl-Alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: Curl/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/curl:alpine
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: Curl
          cache: true
  Build-Java-Alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: Java/Alpine/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/java:alpine
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: Java/Alpine
          cache: true
  Build-BFG-Alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: BFG/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/bfg:alpine
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: BFG
          cache: true

  Build-CoreDNS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: CoreDNS/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/coredns-scratch:scratch
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: CoreDNS
          cache: true

  Build-Sonarr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: MediaServer/Sonarr/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/media-sonarr:latest
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: MediaServer/Sonarr
          cache: true

  Build-Radarr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: MediaServer/Radarr/Dockerfile
          name: docker.pkg.github.com/kristianfjones/docker-images/media-radarr:latest
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
          registry: docker.pkg.github.com
          path: MediaServer/Radarr
          cache: true
